### ISSUE TITLE
data upload

### ISSUE THREAD

**Issue by ctorney** [microsoft/aerial_wildlife_detection#23]
Hi
I'm having issues trying to upload images into a new project. I have the fileserver running on the same machine as the labelUI. When uploading images and clicking scan untracked sometimes the images show up in the listview, but sometimes it hangs with the 'loading...' message.

When it has loaded the images Add all didn't work and I could only upload 100 images at a time. This error was shown on the console a few times but not consistently:
```
Traceback (most recent call last):
  File "/anaconda/envs/py37_tensorflow/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/anaconda/envs/py37_tensorflow/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ctorney/workspace/aerial_wildlife_detection/modules/DataAdministration/backend/celery_interface.py", line 52, in addExistingImages
    return worker.addExistingImages(project, imageList)
  File "/home/ctorney/workspace/aerial_wildlife_detection/modules/DataAdministration/backend/dataWorker.py", line 436, in addExistingImages
    imgs_add = list(set(imgs_candidates).intersection(set(imageList)))
TypeError: unhashable type: 'dict'
```

Thanks

**Comment by bkellenb** [comment]
Hi Colin,

Thank you for the error report. I noticed the "Add all" problem; only the images from the viewer would be added. The latest version (1.9.201001d) _should_ now instead look for all untracked images and try to add them at once.

Regarding the error: I added a quick ﬁx as a workaround, but I will invest more time to ﬁnd the error source and resolve it properly. 

Please let me know if it worked and if you encounter any more issues. Thank you.

**Comment by ctorney** [comment]
Thanks - that's worked. I managed to upload all the images. I still have an issue on many of the admin pages that it hangs with the "loading..." message, not sure if this is to do with my setup or maybe a setting I have wrong (I noticed I have to relogin a lot more than with v1).
