### ISSUE TITLE
Python module version issues

### ISSUE THREAD

**Issue by stewartmacdonald** [microsoft/aerial_wildlife_detection#26]
Has anyone successfully built this from scratch recently? I'm getting lots of issues with python modules not being found. Looks like pull request #25 tries to fix one of these (`No module named 'kombu.five'`) by pinning `celery` to 4.4.7 in `docker/requirements.txt`, but that didn't work for me. Adding `kombu == 4.6.11` to `docker/requirements.txt` fixed the `kombu.five` issue, but then I get the same thing with vine.five. Adding `vine==1.3.0` solves that, but then I get an issue with `celery.task`. Can anyone with a working image supply a list of the correct module versions that I can add to the `requirements.txt` file? I'm not particularly experienced with docker and python, so apologies if this is something simple that I'm stuffing up.

```
smacdonald@ordovicia:~/docker/cameratrapping/aerial_wildlife_detection/docker$ sudo docker-compose up
Recreating docker_aide_app_1 ... done
Attaching to docker_aide_app_1
aide_app_1  | Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
aide_app_1  | Executing: /lib/systemd/systemd-sysv-install enable redis-server
aide_app_1  | Starting redis-server: redis-server.
aide_app_1  | =============================
aide_app_1  | Setup of database IS STARTING
aide_app_1  | =============================
aide_app_1  |  * Restarting PostgreSQL 10 database server
aide_app_1  |    ...done.
aide_app_1  | GRANT
aide_app_1  | NOTICE:  extension "uuid-ossp" already exists, skipping
aide_app_1  | CREATE EXTENSION
aide_app_1  | GRANT
aide_app_1  | Traceback (most recent call last):
aide_app_1  |   File "setup/setupDB.py", line 14, in <module>
aide_app_1  |     from modules import Database, UserHandling
aide_app_1  |   File "/home/aide/app/modules/__init__.py", line 24, in <module>
aide_app_1  |     from .AIController.app import AIController
aide_app_1  |   File "/home/aide/app/modules/AIController/app.py", line 9, in <module>
aide_app_1  |     from modules.AIController.backend.middleware import AIMiddleware
aide_app_1  |   File "/home/aide/app/modules/AIController/backend/middleware.py", line 23, in <module>
aide_app_1  |     from modules.AIController.taskWorkflow.workflowTracker import WorkflowTracker
aide_app_1  |   File "/home/aide/app/modules/AIController/taskWorkflow/workflowTracker.py", line 15, in <module>
aide_app_1  |     from celery.task.control import revoke
aide_app_1  | ModuleNotFoundError: No module named 'celery.task'
aide_app_1  | Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
aide_app_1  | Executing: /lib/systemd/systemd-sysv-install enable postgresql
aide_app_1  |  * Starting PostgreSQL 10 database server
aide_app_1  |    ...done.
aide_app_1  | ==============================
aide_app_1  | Setup of database IS COMPLETED
aide_app_1  | ==============================
```

**Comment by Wytamma** [comment]
I solved this by pinning `celery[redis,auth,msgpack]==4.4.7` & `kombu==4.6.11` in the `docker/requirements.txt` file. 

Note: == not >=

**Comment by bkellenb** [comment]
Thank you @Wytamma !
Did this work for you @stewartmacdonald ?

**Comment by stewartmacdonald** [comment]
Yep, I can successfully get a docker container up and running. Looks like there are some issues getting the actual AIDE application working, but I haven't tried to debug that yet.
